import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NavLinks from "@/components/Nav-links";
import Announcement from "@/components/Announcement";
import TopUsers from "@/components/TopUsers";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import TopLoader from "@/components/TopLoader";
import ReactQueryProvider from "@/components/context-providers/ReactQueryProvider";
import MobileNavLinks from "@/components/MobileNavLinks";
import InitUser from "@/components/InitUser";
import { Suspense } from "react";
import { SessionProvider } from "next-auth/react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "medial-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-zinc-950 text-zinc-50`}>
           <SessionProvider>
            <ReactQueryProvider>
            <NextSSRPlugin
                 routerConfig={extractRouterConfig(ourFileRouter)} />
            <InitUser/>
       <Navbar/>
        <main className="flex  items-start py-5  gap-2 lg:px-10 px-2">
   <div className="left hidden lg:flex flex-col gap-2 sticky top-2">
   <NavLinks/>
 <div className=" flex-col hidden lg:flex">
 <Announcement/>
 </div>
   </div>
   <MobileNavLinks/>
        {children}
        <div className="right hidden  lg:flex flex-col sticky top-2 gap-2">
  <Suspense  fallback='Loading'>
  <TopUsers/>
  </Suspense>
   </div> 
        </main>
        <div className="block h-[100px]"></div>
            </ReactQueryProvider>
            </SessionProvider>
      </body>
    </html>
  );
}
